version: "3"
services:
  node:
    restart: always
    build: .
    depends_on:
      - mongo
    ports:
      - 3005:3005
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
volumes:
  mongodb:
  cache:
