version: "3"
services:
  node:
    restart: always
    build: .
    depends_on:
      - mongo
    ports:
      - 3005:3005
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - mongobackup:/backup
  redis:
    image: redislabs/redismod:latest
    ports:
      - 6379:6379
    volumes:
      - cache:/data
volumes:
  mongodb:
  mongobackup:
  cache:
